[package]
name = "libremarkable-utils"
description = "Shared types and logic for reMarkable tablet tooling"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
tar = { workspace = true }
zip = { workspace = true }
